#!/usr/bin/env python

from os import listdir, path, makedirs
from shutil import move
import re
import logging

logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)

def find_package_dir(fname):
    pk = ''
    packdirs = []
    for line in open(fname):
        if "package " in line:
            if pk:
                logging.info("Warning: multiple package declarations in {0}".format(fname))
            else:
                line = re.sub(r'^package ', '', line)
                if line:
                    line = re.sub(r';$', '', line.rstrip())
                    if line:
                        packdirs = line.split(".")
    if packdirs:
        return "/".join(packdirs)
    else:
        return ''

mypath = "."
subfiles = [f for f in listdir(mypath) if ".java" in f]

for javafile in subfiles:
    packdir = find_package_dir(javafile)
    logging.info('moving {0} into {1}'.format(javafile, packdir))
    if packdir:
        if not path.isdir(packdir):
            makedirs(packdir)
        move(javafile, packdir)

